# Generated by Django 5.1.7 on 2025-08-06 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('sms', 'SMS Provider'), ('call', 'Call Provider'), ('whatsapp', 'WhatsApp Provider'), ('combined', 'Combined Provider')], max_length=20)),
                ('provider_class', models.CharField(max_length=200)),
                ('configuration', models.JSONField(default=dict)),
                ('supported_countries', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('cost_per_message', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('average_response_time_ms', models.IntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('is_healthy', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('provider_name', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('sms', 'SMS'), ('call', 'Voice Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('provider_name', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('prayer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='communicati_user_id_c556f7_idx'), models.Index(fields=['communication_type', 'created_at'], name='communicati_communi_f50f8e_idx'), models.Index(fields=['provider_name', 'created_at'], name='communicati_provide_075501_idx'), models.Index(fields=['success', 'created_at'], name='communicati_success_5eb556_idx')],
            },
        ),
    ]
