# Generated by Django 5.1.7 on 2025-11-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_add_africastalking_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('call_type', models.CharField(max_length=20)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='communicati_phone_n_caf47b_idx'), models.Index(fields=['session_id'], name='communicati_session_b0cc8f_idx')],
            },
        ),
    ]
