# Generated by Django 5.1.7 on 2025-11-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_voicecallsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When message was delivered', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], default='unknown', help_text='Delivery status from provider', max_length=20),
        ),
        migrations.CreateModel(
            name='CountryProviderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 2-letter country code (e.g., NG, US)', max_length=2)),
                ('communication_type', models.CharField(choices=[('sms', 'SMS'), ('call', 'Voice Call'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('provider_priority', models.JSONField(default=list, help_text='List of provider names in priority order (first = highest priority)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Provider Preference',
                'verbose_name_plural': 'Country Provider Preferences',
                'ordering': ['country_code', 'communication_type'],
                'unique_together': {('country_code', 'communication_type')},
            },
        ),
    ]
