# Generated by Django 5.1.7 on 2025-05-30 05:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='ABUJA', max_length=100)),
                ('country', models.CharField(default='NIGERIA', max_length=100)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('midnight_utc', models.TimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(choices=[(1, 'Muslim World League'), (2, 'Islamic Society of North America'), (3, 'Egyptian General Authority of Survey'), (4, 'Umm Al-Qura University, Makkah'), (5, 'University of Islamic Sciences, Karachi'), (6, 'Institute of Geophysics, University of Tehran'), (7, 'Shia Ithna-Ashari, Leva Institute, Qum'), (8, 'Gulf Region'), (9, 'Kuwait'), (10, 'Qatar'), (11, 'Majlis Ugama Islam Singapura, Singapore'), (12, 'Union Organization Islamic de France'), (13, 'Diyanet İşleri Başkanlığı, Turkey'), (14, 'Spiritual Administration of Muslims of Russia'), (15, 'Moonsighting Committee'), (16, 'Dubai, UAE - Batoul Apps Team')], default=1)),
                ('name', models.CharField(default='Muslim World League', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsak', models.IntegerField(blank=True, null=True)),
                ('fajr', models.IntegerField(blank=True, null=True)),
                ('sunrise', models.IntegerField(blank=True, null=True)),
                ('dhuhr', models.IntegerField(blank=True, null=True)),
                ('asr', models.IntegerField(blank=True, null=True)),
                ('maghrib', models.IntegerField(blank=True, null=True)),
                ('sunset', models.IntegerField(blank=True, null=True)),
                ('isha', models.IntegerField(blank=True, null=True)),
                ('midnight', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_prayer_summary_enabled', models.BooleanField(default=True)),
                ('daily_prayer_summary_message_method', models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10, null=True)),
                ('notification_before_prayer_enabled', models.BooleanField(default=True)),
                ('notification_before_prayer', models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS')], default='sms', max_length=10, null=True)),
                ('notification_time_before_prayer', models.IntegerField(blank=True, default=15, help_text='Number of minutes before prayer time to send notification', null=True)),
                ('adhan_call_enabled', models.BooleanField(default=True)),
                ('adhan_call_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Phone Call')], default='call', max_length=10)),
                ('notification_methods', models.CharField(blank=True, choices=[('email', 'Email'), ('call', 'Call'), ('sms', 'SMS')], max_length=10, null=True)),
                ('utc_time_for_1159', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
