# Generated by Django 5.1.7 on 2025-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='adhan_call_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Phone Call'), ('text', 'Text Message')], default='call', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='daily_prayer_summary_message_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='notification_before_prayer',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10),
        ),
    ]
