# Generated by Django 5.1.7 on 2025-07-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='show_last_third',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='adhan_call_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Phone Call'), ('text', 'Text Message')], default='email', max_length=10),
        ),
    ]
