# Generated by Django 5.1.7 on 2025-11-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_twitter_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Whether to fetch prayer times and send notifications to this user'),
        ),
    ]
