# Generated by Django 3.2.12 on 2023-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayermethod',
            name='sn',
            field=models.IntegerField(choices=[(1, 'Muslim World League'), (2, 'Islamic Society of North America'), (3, 'Egyptian General Authority of Survey'), (4, 'Umm Al-Qura University, Makkah'), (5, 'University of Islamic Sciences, Karachi'), (6, 'Institute of Geophysics, University of Tehran'), (7, 'Shia Ithna-Ashari, Leva Institute, Qum'), (8, 'Gulf Region'), (9, 'Kuwait'), (10, 'Qatar'), (11, 'Majlis Ugama Islam Singapura, Singapore'), (12, 'Union Organization Islamic de France'), (13, 'Diyanet İşleri Başkanlığı, Turkey'), (14, 'Spiritual Administration of Muslims of Russia'), (15, 'Moonsighting Committee'), (16, 'Dubai, UAE - Batoul Apps Team')], default=1),
        ),
        migrations.AlterField(
            model_name='prayermethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
