# Generated by Django 3.2.12 on 2023-10-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231028_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Country',
            new_name='country',
        ),
    ]
