services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - muadhin_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-muadhin_db}
      POSTGRES_USER: ${POSTGRES_USER:-muadhin_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - muadhin_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-muadhin_user} -d ${POSTGRES_DB:-muadhin_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  web:
    build:
      context: .
      target: production
    environment:
      - DJANGO_ENV=production
      - DEBUG=0
      - DATABASE_URL=postgresql://${POSTGRES_USER:-muadhin_user}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-muadhin_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
      - AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
      - AFRICASTALKING_PHONE_NUMBER=${AFRICASTALKING_PHONE_NUMBER}
      - AFRICASTALKING_CALLER_ID=${AFRICASTALKING_CALLER_ID}
      - DOMAIN=${DOMAIN}
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - muadhin_network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/staticfiles:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - muadhin_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  celery:
    build:
      context: .
      target: production
    command: celery
    environment:
      - DJANGO_ENV=production
      - DEBUG=0
      - DATABASE_URL=postgresql://${POSTGRES_USER:-muadhin_user}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-muadhin_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
      - AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
      - AFRICASTALKING_PHONE_NUMBER=${AFRICASTALKING_PHONE_NUMBER}
      - AFRICASTALKING_CALLER_ID=${AFRICASTALKING_CALLER_ID}
      - DOMAIN=${DOMAIN}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - muadhin_network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  celery-beat:
    build:
      context: .
      target: production
    command: celery-beat
    environment:
      - DJANGO_ENV=production
      - DEBUG=0
      - DATABASE_URL=postgresql://${POSTGRES_USER:-muadhin_user}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-muadhin_db}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
      - AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
      - AFRICASTALKING_PHONE_NUMBER=${AFRICASTALKING_PHONE_NUMBER}
      - AFRICASTALKING_CALLER_ID=${AFRICASTALKING_CALLER_ID}
      - DOMAIN=${DOMAIN}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    networks:
      - muadhin_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  flower:
    build:
      context: .
      target: production
    command: flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - muadhin_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data:
  redis_data:
  static_volume:

networks:
  muadhin_network:
    driver: bridge