version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: muadhin_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    container_name: muadhin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=muadhin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: muadhin_web
    command: web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - PORT=8000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PGDATABASE=muadhin
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: muadhin_celery_worker
    command: worker
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PGDATABASE=muadhin
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build: .
    container_name: muadhin_celery_beat
    command: beat
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PGDATABASE=muadhin
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: