[build]
builder = "NIXPACKS"
# Skip collectstatic during build
buildCommand = "echo 'Skipping collectstatic during build phase'"

[deploy]
# Run with verbose output for debugging
startCommand = "/app/docker-entrypoint.sh web"
# Use the simple health check that doesn't depend on database
healthcheckPath = "/simple-health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.10.5"