[build]
builder = "NIXPACKS"
# Skip collectstatic during build
buildCommand = "echo 'Skipping collectstatic during build phase'"

[deploy]
# Run with simple entry
startCommand = "/app/docker-entrypoint.sh web"
# Use a very simple health check that doesn't depend on database
healthcheckPath = "/ping/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.10.5"
SKIP_MIGRATIONS = "no"  # Set to "yes" to skip migrations during startup for testing