# Generated by Django 3.2.12 on 2023-11-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_date', models.DateField(blank=True, null=True)),
                ('weekday_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_email_notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(max_length=50)),
                ('prayer_time', models.TimeField(blank=True, null=True)),
                ('is_sms_notified', models.BooleanField(default=False)),
                ('is_phonecall_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalatTracker.dailyprayer')),
            ],
        ),
    ]
