# Generated by Django 5.1.7 on 2025-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_date', models.DateField(blank=True, null=True)),
                ('weekday_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_email_notified', models.BooleanField(default=False)),
                ('is_sms_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(max_length=50)),
                ('prayer_time', models.TimeField(blank=True, null=True)),
                ('is_sms_notified', models.BooleanField(default=False)),
                ('is_phonecall_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
