# Generated by Django 5.1.7 on 2025-05-31 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SalatTracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_prayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayertime',
            name='daily_prayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_times', to='SalatTracker.dailyprayer'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprayer',
            unique_together={('user', 'prayer_date')},
        ),
        migrations.AlterUniqueTogether(
            name='prayertime',
            unique_together={('daily_prayer', 'prayer_name')},
        ),
    ]
