"""
Django settings for muadhin project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab
import dj_database_url



load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Render deployment
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME, 'localhost', '127.0.0.1', 'api.almuadhin.com', 'muadhin-frontend-gold.vercel.app']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'muadhin.onrender.com', 'api.almuadhin.com', 'muadhin-frontend-gold.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'users',
    'SalatTracker',
    'rest_framework',
    'drf_yasg',
    'rest_framework_simplejwt',
    'corsheaders',
    'subscriptions',
    'communications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'muadhin.urls'

AUTH_USER_MODEL = 'users.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'muadhin.wsgi.application'

# Email template for subscription notifications
EMAIL_TEMPLATES = {
    'subscription_activated': 'subscriptions/emails/subscription_activated.html',
    'subscription_expired': 'subscriptions/emails/subscription_expired.html',
    'trial_ending': 'subscriptions/emails/trial_ending.html',
}

# Database Configuration
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production/Deployment with DATABASE_URL (Supabase, Heroku, Render, etc.)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
else:
    # Local development fallback
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Additional Django settings for memory optimization
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB max upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5MB max file upload

# Django query optimizations
# DATABASES['default']['OPTIONS'].update({
#     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#     'charset': 'utf8mb4',
# })

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files with WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'file_cache/'),  # Use os.path.join to create an absolute path to the desired cache directory path
    }
}

ADHAN_AUDIO_URL = os.environ.get(
      'ADHAN_AUDIO_URL',
      f"{os.environ.get('SITE_URL', 'http://localhost')}/static/audio/adhan/adhan_filename.mp3"
  )

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
# CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Use the URL of your message broker
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Use the same URL as CELERY_BROKER_URL
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_BEAT_SCHEDULE = {
#     # 'schedule_midnight_checks': {
#     #     'task': 'SalatTracker.tasks.schedule_midnight_checks',
#     #     'schedule': crontab(minute='*/2'),  # Run every 2 minutes
#     # },
#     'check_and_schedule_daily_tasks': {
#         'task': 'users.tasks.check_and_schedule_daily_tasks',
#         'schedule': crontab(minute='*/2'),  # Run every 30 minutes
#     },
# }

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PERMISSION_OVERRIDES': {
        '/doc/': ['rest_framework.permissions.AllowAny'],
        '/redoc/': ['rest_framework.permissions.AllowAny'],
        '/swagger/': ['rest_framework.permissions.AllowAny'],
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        },
    },
    'USE_SESSION_AUTH': False,
    'VALIDATOR_URL': None,
    'PERSIST_AUTH': True,
    'DOC_EXPANSION': 'list',
}



# TWILIO 

TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

CORS_ALLOW_ALL_ORIGINS = True

# CSRF Settings for Docker/Development
# For local development and Docker environments
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    'http://localhost',
    'http://127.0.0.1',
    'https://api.almuadhin.com',
    'https://muadhin-frontend-gold.vercel.app'
]

# Add production domains when deploying
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS.extend([
        'https://api.almuadhin.com',
    ])

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')

# MAILGUN SETTINGS
# EMAIL_BACKEND = 'django_mailgun_mime.backends.MailgunMIMEBackend'
# MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY')
# MAILGUN_DOMAIN_NAME = os.getenv('MAILGUN_DOMAIN_NAME')

# Communication Provider Configurations
COMMUNICATION_PROVIDERS = {
    'twilio': {
        'account_sid': os.getenv('TWILIO_ACCOUNT_SID', ''),
        'auth_token': os.getenv('TWILIO_AUTH_TOKEN', ''),
        'phone_number': os.getenv('TWILIO_PHONE_NUMBER', ''),
        'whatsapp_number': os.getenv('TWILIO_WHATSAPP_NUMBER', ''),
        'debug_mode': DEBUG,  # Use debug mode in development
    },
    'africastalking': {
        'username': os.getenv('AFRICASTALKING_USERNAME', ''),
        'api_key': os.getenv('AFRICASTALKING_API_KEY', ''),
        'sender_id': os.getenv('AFRICASTALKING_SENDER_ID', ''),
        'phone_number': os.getenv('AFRICASTALKING_PHONE_NUMBER', ''),  # Your AT number
        'caller_id': os.getenv('AFRICASTALKING_CALLER_ID', ''),        # Caller ID for voice
        'debug_mode': False,  # Live mode - credentials are working
        
        # Voice callback configuration
        'voice_callback_url': f"https://{os.getenv('DOMAIN', 'localhost:8000')}/api/communications/callbacks/africastalking/voice/",
    },
    'nigeria': {
        'api_key': os.getenv('NIGERIA_SMS_API_KEY', ''),
        'sender_id': os.getenv('NIGERIA_SMS_SENDER_ID', 'Muadhin'),
        'api_url': os.getenv('NIGERIA_SMS_API_URL', 'https://api.termii.com/api/sms/send'),
        'debug_mode': DEBUG,
    },
    'india': {
        'api_key': os.getenv('INDIA_SMS_API_KEY', ''),
        'sender_id': os.getenv('INDIA_SMS_SENDER_ID', 'MUADHN'),
        'api_url': os.getenv('INDIA_SMS_API_URL', 'https://api.textlocal.in/send/'),
        'debug_mode': DEBUG,
    },
    # Add more providers as needed
}

# Provider Selection Rules
COMMUNICATION_PROVIDER_RULES = {
    'default_fallback': 'twilio',
    'cost_optimization': True,  # Always try cheaper providers first
    'max_retries': 3,  # Maximum number of providers to try
    'health_check_interval': 3600,  # Check provider health every hour
}

GEONAMES_USERNAME = 'giwabdul'
REST_COUNTRIES_API_URL = 'https://restcountries.com/v3.1'
GEONAMES_API_URL = 'http://api.geonames.org'
LOCATION_CACHE_TIMEOUT = 60 * 60 * 24  # 24 hours
