# Generated by Django 5.1.7 on 2025-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['country', 'sort_order', 'price']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='country',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('NG', 'Nigeria'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar')], default='GLOBAL', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('QAR', 'Qatari Riyal')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic - Salah Reminder'), ('plus', 'Plus - Muaddhin'), ('premium', 'Premium - Qiyam')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('plan_type', 'country')},
        ),
    ]
