# Generated by Django 5.1.7 on 2025-10-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_country_currency_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('plan_type', 'country', 'billing_cycle')},
        ),
    ]
