# Generated by Django 5.1.7 on 2025-11-08 05:37

from django.db import migrations
from django.utils import timezone


def create_basic_plan_and_assign_users(apps, schema_editor):
    """
    Create a free basic plan if it doesn't exist.
    Assign all existing users without subscriptions to this plan (indefinitely - grandfathered).
    """
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    UserSubscription = apps.get_model('subscriptions', 'UserSubscription')
    User = apps.get_model('users', 'CustomUser')

    # Create or get the free basic plan
    basic_plan, created = SubscriptionPlan.objects.get_or_create(
        plan_type='basic',
        country='GLOBAL',
        billing_cycle='monthly',
        defaults={
            'name': 'Basic - Salah Reminder (Free)',
            'currency': 'USD',
            'price': 0.00,
            'description': 'Free basic prayer reminders via email. Perfect for getting started.',
            'is_active': True,
            'sort_order': 0,
            # Email notifications only (no cost)
            'daily_prayer_summary_email': True,
            'daily_prayer_summary_whatsapp': False,
            'pre_adhan_email': True,
            'pre_adhan_sms': False,
            'pre_adhan_whatsapp': False,
            'adhan_call_text': False,
            'adhan_call_audio': False,
            # Basic features
            'max_notifications_per_day': 10,
            'priority_support': False,
            'custom_adhan_sounds': False,
        }
    )

    if created:
        print(f"✅ Created free basic plan: {basic_plan.name}")
    else:
        print(f"✅ Basic plan already exists: {basic_plan.name}")

    # Assign all existing users without subscriptions to the basic plan (indefinitely)
    users_without_subscription = User.objects.exclude(
        id__in=UserSubscription.objects.values_list('user_id', flat=True)
    )

    subscriptions_created = 0
    for user in users_without_subscription:
        UserSubscription.objects.create(
            user=user,
            plan=basic_plan,
            status='active',
            start_date=timezone.now(),
            end_date=None,  # Grandfathered - no expiry for existing users
        )
        subscriptions_created += 1

    print(f"✅ Assigned {subscriptions_created} existing users to basic plan (indefinitely)")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by removing the basic plan and subscriptions.
    This is optional - you may want to keep the data.
    """
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')

    # Note: We don't delete user subscriptions as that would lose data
    # We only delete the basic plan if needed
    SubscriptionPlan.objects.filter(
        plan_type='basic',
        country='GLOBAL',
        price=0.00
    ).delete()
    print("✅ Removed basic plan")


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_update_unique_constraint'),
        ('users', '0004_add_receive_notifications_field'),  # Ensure user field exists
    ]

    operations = [
        migrations.RunPython(create_basic_plan_and_assign_users, reverse_migration),
    ]
