# Generated by Django 5.1.7 on 2025-11-08 00:00

from django.db import migrations


def create_test_plans(apps, schema_editor):
    """
    Create two test subscription plans:
    1. Pro Plan (Test) - SMS notifications for pre-adhan
    2. Premium Plan (Test) - SMS + Phone call for adhan
    """
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')

    # Create Pro Plan (Test) - SMS for notifications
    pro_plan, created = SubscriptionPlan.objects.get_or_create(
        plan_type='plus',
        country='GLOBAL',
        billing_cycle='monthly',
        defaults={
            'name': 'Pro - Muaddhin (Test)',
            'currency': 'USD',
            'price': 9.99,
            'description': 'Test plan with SMS notifications for pre-adhan reminders. Perfect for testing SMS integration.',
            'is_active': True,
            'sort_order': 1,
            # Daily summaries via email
            'daily_prayer_summary_email': True,
            'daily_prayer_summary_whatsapp': False,
            # Pre-adhan notifications via SMS
            'pre_adhan_email': True,
            'pre_adhan_sms': True,  # SMS enabled
            'pre_adhan_whatsapp': False,
            # No phone calls for Pro
            'adhan_call_text': False,
            'adhan_call_audio': False,
            # Enhanced features
            'max_notifications_per_day': 20,
            'priority_support': False,
            'custom_adhan_sounds': False,
        }
    )

    if created:
        print(f"✅ Created Pro test plan: {pro_plan.name}")
    else:
        print(f"✅ Pro test plan already exists: {pro_plan.name}")

    # Create Premium Plan (Test) - SMS + Phone call for adhan
    premium_plan, created = SubscriptionPlan.objects.get_or_create(
        plan_type='premium',
        country='GLOBAL',
        billing_cycle='monthly',
        defaults={
            'name': 'Premium - Qiyam (Test)',
            'currency': 'USD',
            'price': 19.99,
            'description': 'Test plan with SMS notifications and phone call for adhan. Complete testing experience with all features.',
            'is_active': True,
            'sort_order': 2,
            # Daily summaries via email, SMS, and WhatsApp
            'daily_prayer_summary_email': True,
            'daily_prayer_summary_sms': True,  # SMS enabled for daily summaries
            'daily_prayer_summary_whatsapp': True,
            # Pre-adhan notifications via SMS
            'pre_adhan_email': True,
            'pre_adhan_sms': True,  # SMS enabled
            'pre_adhan_whatsapp': False,
            # Phone call for adhan (audio)
            'adhan_call_text': False,
            'adhan_call_audio': True,  # Phone call enabled
            # Premium features
            'max_notifications_per_day': 50,
            'priority_support': True,
            'custom_adhan_sounds': True,
        }
    )

    if created:
        print(f"✅ Created Premium test plan: {premium_plan.name}")
    else:
        print(f"✅ Premium test plan already exists: {premium_plan.name}")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by removing the test plans.
    """
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')

    # Delete Pro and Premium test plans
    deleted_count = SubscriptionPlan.objects.filter(
        plan_type__in=['plus', 'premium'],
        country='GLOBAL',
        name__icontains='Test'
    ).delete()[0]

    print(f"✅ Removed {deleted_count} test plan(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_create_basic_plan_and_assign_users'),
    ]

    operations = [
        migrations.RunPython(create_test_plans, reverse_migration),
    ]
