# Generated by Django 5.1.7 on 2025-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_create_test_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_prayer_summary_sms',
            field=models.BooleanField(default=False),
        ),
    ]
