# Generated by Django 5.1.7 on 2025-11-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionplan_daily_prayer_summary_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_notifications_per_day',
            field=models.IntegerField(default=15),
        ),
    ]
